name: Deploy from master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm i && npm run build
      - run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      
